const permissions = {
    Owner: {
        ChangePassword: {
            "id": 11,
            "role_permission_type_id": 4,
            "role_id": 1,
            "name": "Change Password",
            "name_vi": "Đổi Mật Khẩu",
            "code": "change_password",
            "description": "ChangePassword ChangePassword",
            "status": "true",
            "view": "true",
            "new": "false",
            "edit": "true",
            "delete": "false",
        },
        SignUp: {
            "id": 16,
            "role_permission_type_id": 4,
            "role_id": 1,
            "name": "Sign Up",
            "name_vi": "Đăng Ký",
            "code": "sign_up",
            "description": "Sign Up Sign Up",
            "status": "true",
            "view": "false",
            "new": "false",
            "edit": "false",
            "delete": "false",
        },
        Login: {
            "id": 17,
            "role_permission_type_id": 4,
            "role_id": 1,
            "name": "Login",
            "name_vi": "Đăng Nhập",
            "code": "login",
            "description": "Login Login",
            "status": "true",
            "view": "true",
            "new": "false",
            "edit": "true",
            "delete": "false",
        },
    },
}
module.exports = permissions;