const users = {
    Owner: {
        "id": 1,
        "fullname": "Owner",
        "select_username": "email",
        "gender": true,
        "username": "owner",
        "password": "owner",
        "email": "owner@gmail.com",
        "phone": "0932221911",
        "address": "123 NTT",
        "is_active": true,
        "role_id": 1,
        "organization_id": 1,
        "is_trial": false
    },
    Manager: {
        "id": 2,
        "fullname": "Manager",
        "select_username": "email",
        "gender": true,
        "username": "manager",
        "password": "manager",
        "email": "manager@gmail.com",
        "phone": "0932221912",
        "address": "123 NTT",
        "is_active": true,
        "role_id": 2,
        "organization_id": 1,
        "is_trial": false
    },
    Admin: {
        "id": 3,
        "fullname": "Administration",
        "select_username": "email",
        "gender": true,
        "username": "admin",
        "password": "admin",
        "email": "admin@gmail.com",
        "role_id": 3,
        "organization_id": 2,
        "phone": "0888888888",
        "address": "123 NTT",
        "is_active": true,
        "is_trial": false
    },
    Mentor : {
        "id": 4,
        "fullname": "Mentor",
        "select_username": "email",
        "gender": true,
        "username": "mentor",
        "password": "mentor",
        "email": "mentor@gmail.com",
        "role_id":4 ,
        "organization_id": 2,
        "phone": "",
        "address": "123 NTT",
        "is_active": true,
        "is_trial": false
    },
    Mentee : {
        "id": 5,
        "fullname": "Mentee",
        "select_username": "email",
        "gender": true,
        "username": "mentee",
        "password": "mentee",
        "email": "mentee@gmail.com",
        "role_id": 5,
        "organization_id": 2,
        "phone": "",
        "address": "123 NTT",
        "is_active": true,
        "is_trial": false
    },
    AnMentee: {
        "id": 6,
        "fullname": "Thien An",
        "select_username": "email",
        "gender": true,
        "username": "thienan",
        "password": "thienan",
        "email": "thienan@gmail.com",
        "role_id": 4,
        "organization_id": 3,
        "phone": "0812354222",
        "address": "123 NTT",
        "is_active": true,
        "is_trial": false,
        "create_by": 1
    },
    AnMentor: {
        "id": 7,
        "select_username": "email",
        "fullname": "Thien An",
        "gender": true,
        "username": "thienanmentor",
        "password": "thienanmentor",
        "email": "thienanmentor@gmail.com",
        "role_id": 5,
        "organization_id": 1,
        "phone": "08123542222",
        "address": "123 NTT",
        "is_active": true,
        "is_trial": false,
        "create_by": 1
    },
};
module.exports = users;